version: "3.7"
services:
  movie-manage:
    build: .
    container_name: movie-manage
    image: movie-manage:latest
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "80:8080"
    networks:
      - rest-network
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --mysql-native-password=ON
    image: mysql:latest
    networks:
      - rest-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=movie_manage_db
      - MYSQL_USER=restouser
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

networks:
  rest-network:
    driver: bridge
volumes:
  mysql-data:
  java-data:
