version: "3.7"
services:
  movie-manage:
    build: .
    container_name: movie-manage
    image: movie-manage:latest
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "80:8080"
    networks:
      - movie-network
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - movie-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka123
      - MYSQL_DATABASE=movie_manage_db
      - MYSQL_USER=movieuser
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

networks:
  movie-network:
    driver: bridge
volumes:
  mysql-data:
  java-data:
