version: "3.7"
services:
  movie-manage:
    build: .
    container_name: movie-manage
    image: movie-manage:latest
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 8080:8080
    networks:
      - rest-network
    volumes:
      - java-data:/app/uploads
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    image: mysql
    networks:
      - rest-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka123
      - MYSQL_DATABASE=movie_manage_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=lozinka123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

networks:
  rest-network:
    driver: bridge

volumes:
  mysql-data:
  java-data:
